name: ad_snrna
dependencies:
  - python==3.11
  - pip
  - pip:
      - kb-python==0.29.5
      - scanpy==1.10.2
      - anndata==0.10.8
      - pandas==2.2.2
      - numpy==1.26.4
      - scipy==1.13.1
      - matplotlib==3.9.2
      - seaborn==0.13.2
      - python-igraph==0.11.5
      - leidenalg==0.10.2
      - scikit-misc==0.5.1